CREATE TABLE IF NOT EXISTS account
(
    account_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(255),
    email   VARCHAR(255) NOT NULL
        CONSTRAINT uq_account_email UNIQUE
);

CREATE TABLE IF NOT EXISTS post
(
    post_id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title     VARCHAR(255) NOT NULL,
    created   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    content   TEXT,
    published BOOLEAN      NOT NULL DEFAULT false,
    account_id   INTEGER
        CONSTRAINT fk_post_account_id REFERENCES account (account_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS profile
(
    profile_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bio        TEXT,
    account_id    INTEGER
        CONSTRAINT fk_profile_account_id REFERENCES account (account_id) ON DELETE CASCADE,
    CONSTRAINT uq_profile_account_id UNIQUE (account_id)
);
